/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import datos.AlmacenamientoBeneficios;
import datos.AlmacenamientoBeneficiosEstudiantes;
import datos.AlmacenamientoCarreras;
import datos.AlmacenamientoEstudiante;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lógica.Carreras;
import lógica.Estudiante;
import vista.DlgNuevoBeneficio;

/**
 *
 * @author Génesis Leiva
 * @author Ariana Araya
 */
public class DlgGestionEstudiantes extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgGestionEstudiantes.class.getName());
    protected AlmacenamientoEstudiante listaEstudiantes;
    protected AlmacenamientoCarreras listaCarreras;
    protected AlmacenamientoBeneficiosEstudiantes listaBeneficioEstudiante;
    protected AlmacenamientoBeneficios listaBeneficios;
    private DefaultTableModel tblModel;

    /**
     * Creates new form DlgGestionEstudiantes
     */
    public DlgGestionEstudiantes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DlgGestionEstudiantes(java.awt.Frame parent, boolean modal, AlmacenamientoEstudiante listaEstudiantes,
            AlmacenamientoCarreras listaCarreras, AlmacenamientoBeneficiosEstudiantes listaBeneficioEstudiante, AlmacenamientoBeneficios listaBeneficios) {
        super(parent, modal);
        initComponents();
        this.listaEstudiantes = listaEstudiantes;
        this.listaCarreras = listaCarreras;
        this.listaBeneficioEstudiante = listaBeneficioEstudiante;
        this.listaBeneficios = listaBeneficios;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBeneficios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCant.setText("Cantidad de registros:");

        txtCant.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBeneficios.setText("Beneficios");
        btnBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeneficiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBeneficios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String titulo[] = {"Cédula", "Nombre", "Carnet", "Carrera", "Ingreso", "Egreso"};
        Estudiante estudiantes;
        tblModel = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaEstudiantes.getListaEstudiantes().size(); i++) {
            estudiantes = listaEstudiantes.getListaEstudiantes().get(i);

            if (String.valueOf(estudiantes.getCed()).contains(txtBuscar.getText().toLowerCase())
                    || estudiantes.getNom().toLowerCase().contains(txtBuscar.getText().toLowerCase())
                    || String.valueOf(estudiantes.getCarnet()).contains(txtBuscar.getText().toLowerCase())
                    || String.valueOf(estudiantes.getCarrera()).contains(txtBuscar.getText().toLowerCase())) {
                Object row[] = {listaEstudiantes.getListaEstudiantes().get(i).getCed(),
                    listaEstudiantes.getListaEstudiantes().get(i).getNom(),
                    listaEstudiantes.getListaEstudiantes().get(i).getCarnet(),
                listaEstudiantes.getListaEstudiantes().get(i).getCarrera()};
                tblModel.addRow(row);
            }
        }

        tblEstudiantes.setModel(tblModel);
        txtCant.setText(String.valueOf(tblEstudiantes.getRowCount()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNuevoEstudiante win = new DlgNuevoEstudiante(null, true,
                listaEstudiantes, listaCarreras);
        win.setTitle("Agregar Estudiante");
        win.setVisible(true);
        this.listaEstudiantes = win.listaEstudiantes;
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblEstudiantes.getSelectedRowCount() == 1) {
            int pos = tblEstudiantes.getSelectedRow();
            int carnet = Integer.parseInt(tblEstudiantes.getValueAt(tblEstudiantes.getSelectedRow(), 2).toString());

            Estudiante estudiante = listaEstudiantes.buscarCarnet(carnet);

            if (estudiante != null) {
                DlgNuevoEstudiante winEditar = new DlgNuevoEstudiante(null, true, listaEstudiantes, listaCarreras, estudiante, pos);

                winEditar.setTitle("Editar Estudiante");
                winEditar.setLocationRelativeTo(null);
                winEditar.setVisible(true);

                this.listaEstudiantes = winEditar.listaEstudiantes;
            } else {
                JOptionPane.showMessageDialog(this, "Estudiante no encontrado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 Estudainte");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblEstudiantes.getSelectedRowCount() == 1) {
            int carnet = Integer.parseInt(tblEstudiantes.getValueAt(tblEstudiantes.getSelectedRow(), 2).toString());

            int resp = JOptionPane.showConfirmDialog(this, "Quiere eliminar el estudiante");

            Estudiante estudiante = listaEstudiantes.buscarCarnet(carnet);
            if (resp == 0) {  //Sí quiere eliminar el puesto
                if (listaEstudiantes.eliminarEstudiante(estudiante)) {
                    JOptionPane.showMessageDialog(this, "Estudiante eliminado");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 Estudiante");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeneficiosActionPerformed
        if (tblEstudiantes.getSelectedRowCount() == 1) {
            int fila = tblEstudiantes.getSelectedRow();
            int cedula = Integer.parseInt(tblEstudiantes.getValueAt(fila, 0).toString());

            Estudiante estudiante = listaEstudiantes.buscarCedula(cedula);
            if (estudiante != null) {
                DlgAsignarBeneficios dialog = new DlgAsignarBeneficios(null, true, estudiante, listaBeneficios, listaBeneficioEstudiante);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un estudiante");
        }
    }//GEN-LAST:event_btnBeneficiosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        muestraTabla();
    }//GEN-LAST:event_formWindowActivated

    private void muestraTabla() {
        String titulo[] = {"Cédula", "Nombre", "Carnet", "Carrera", "Ingreso", "Egreso"};

        tblModel = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaEstudiantes.getListaEstudiantes().size(); i++) {
            Carreras c = listaCarreras.buscarId(listaEstudiantes.getListaEstudiantes().get(i).getCarrera());

            String nombreCarrera;
            if (c != null) {
                nombreCarrera = c.getNomCarrera();
            } else {
                nombreCarrera = "Carrera no encontrada"; 
            }

            Object row[] = {listaEstudiantes.getListaEstudiantes().get(i).getCed(),
                listaEstudiantes.getListaEstudiantes().get(i).getNom(), listaEstudiantes.getListaEstudiantes().get(i).getCarnet(),
                nombreCarrera,
                listaEstudiantes.getListaEstudiantes().get(i).getFechaIngreso(),
                listaEstudiantes.getListaEstudiantes().get(i).getFechaEgreso()
            };
            tblModel.addRow(row);
        }

        tblEstudiantes.setModel(tblModel);
        txtCant.setText(String.valueOf(tblEstudiantes.getRowCount()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgGestionEstudiantes dialog = new DlgGestionEstudiantes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeneficios;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
