/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import datos.AlmacenamientoBeneficios;
import datos.AlmacenamientoBeneficiosEstudiantes;
import datos.AlmacenamientoCarreras;
import datos.AlmacenamientoEstudiante;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lógica.Beneficios;
import lógica.Carreras;
import lógica.Estudiante;

/**
 *
 * @author Mauricio
 */
public class DlgGestionBeneficios extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgGestionBeneficios.class.getName());
    protected AlmacenamientoBeneficios listaBeneficios;
    private AlmacenamientoEstudiante listaEstudiantes;
    private AlmacenamientoCarreras listaCarreras;
    private AlmacenamientoBeneficiosEstudiantes listaBeneficioEstudiante;
    
    private Estudiante estudiante;
    private DefaultTableModel tblModel;

    /**
     * Creates new form DlgGestionBeneficios
     */
    public DlgGestionBeneficios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DlgGestionBeneficios(java.awt.Frame parent, boolean modal,
            AlmacenamientoBeneficios listaBeneficios) {
        super(parent, modal);
        initComponents();
        this.listaBeneficios = listaBeneficios;
    }

    public DlgGestionBeneficios(java.awt.Frame parent, boolean modal, AlmacenamientoEstudiante listaEstudiante,
            AlmacenamientoBeneficios listaBeneficios,
            AlmacenamientoBeneficiosEstudiantes listaBeneficioEstudiante) {
        super(parent, modal);
        initComponents();
        this.listaEstudiantes = listaEstudiante;
        this.listaBeneficios = listaBeneficios;
        this.listaBeneficioEstudiante = listaBeneficioEstudiante;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBeneficios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCant.setText("Cantidad de registros:");

        txtCant.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblBeneficios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBeneficios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String titulo[] = {"ID", "Nombre", "Monto", "Descripción"};
        Beneficios beneficios;
        tblModel = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaBeneficios.getListaBeneficios().size(); i++) {
            beneficios = listaBeneficios.getListaBeneficios().get(i);

            if (String.valueOf(beneficios.getIdBeneficio()).contains(txtBuscar.getText().toLowerCase())
                    || beneficios.getNomBeneficio().toLowerCase().contains(txtBuscar.getText().toLowerCase())
                    || String.valueOf(beneficios.getMontoBeneficio()).contains(txtBuscar.getText().toLowerCase())) {
                Object row[] = {listaBeneficios.getListaBeneficios().get(i).getIdBeneficio(),
                    listaBeneficios.getListaBeneficios().get(i).getNomBeneficio(),
                    listaBeneficios.getListaBeneficios().get(i).getMontoBeneficio()};
                tblModel.addRow(row);
            }
        }

        tblBeneficios.setModel(tblModel);
        txtCant.setText(String.valueOf(tblBeneficios.getRowCount()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNuevoBeneficio win = new DlgNuevoBeneficio(null, true, listaEstudiantes, listaBeneficios, listaBeneficioEstudiante);
        win.setTitle("Agregar Beneficio");
        win.setVisible(true);
        this.listaBeneficios = win.listaBeneficio;
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblBeneficios.getSelectedRowCount() == 1) {
            int pos = tblBeneficios.getSelectedRow();
            int id = Integer.parseInt(tblBeneficios.getValueAt(tblBeneficios.getSelectedRow(), 0).toString());

            Beneficios beneficios = listaBeneficios.buscarId(id);

            if (beneficios != null) {
                DlgNuevoBeneficio winEditar = new DlgNuevoBeneficio(null, true, listaEstudiantes, listaBeneficios, listaBeneficioEstudiante, beneficios);

                winEditar.setTitle("Editar Beneficio");
                winEditar.setLocationRelativeTo(null);
                winEditar.setVisible(true);

                this.listaBeneficios = winEditar.listaBeneficio;
            } else {
                JOptionPane.showMessageDialog(this, "Beneficio no encontrado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 Beneficio");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblBeneficios.getSelectedRowCount() == 1) {
            int id = Integer.parseInt(tblBeneficios.getValueAt(tblBeneficios.getSelectedRow(), 0).toString());

            int resp = JOptionPane.showConfirmDialog(this, "Quiere eliminar el auto");

            Beneficios beneficios = listaBeneficios.buscarId(id);
            if (resp == 0) {  //Sí quiere eliminar el puesto
                if (listaBeneficios.eliminarBeneficio(beneficios)) {
                    JOptionPane.showMessageDialog(this, "Beneficio eliminado");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 Beneficio");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cargarTabla();
    }//GEN-LAST:event_formWindowActivated
    private void cargarTabla() {
        String[] titulos = {"ID", "Nombre", "Monto", "Descripción"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        for (Beneficios b : listaBeneficios.getListaBeneficios()) {
            Object[] fila = {
                b.getIdBeneficio(),
                b.getNomBeneficio(),
                b.getMontoBeneficio(),
                b.getDescripcion()
            };
            modelo.addRow(fila);
        }

        tblBeneficios.setModel(modelo);
    }
    
    
    private void muestraTabla() {
        String[] titulo = {"ID", "Nombre de la Carrera", "Grado Académico"};

        // Creamos el modelo con celdas editables excepto la columna ID
        tblModel = new DefaultTableModel(null, titulo) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0; // Solo la columna 0 (ID) no editable
            }
        };

        // Llenamos el modelo con los datos de almacenamientoCarreras
        for (Carreras carrera : listaCarreras.getListaCarreras()) {
            if (carrera != null) {
                Object[] row = {
                    carrera.getIdCarrera(),
                    carrera.getNomCarrera(),
                    carrera.getGrado()
                };
                tblModel.addRow(row);
            }
        }

        // Asignamos el modelo a la tabla y actualizamos el contador de registros
        tblBeneficios.setModel(tblModel);
        txtCant.setText(String.valueOf(tblBeneficios.getRowCount()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgGestionBeneficios dialog = new DlgGestionBeneficios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JTable tblBeneficios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
