/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import datos.AlmacenamientoBeneficios;
import datos.AlmacenamientoBeneficiosEstudiantes;
import datos.AlmacenamientoEstudiante;
import javax.swing.JOptionPane;
import lógica.Beneficios;
import lógica.Estudiante;

/**
 *
 * @author Mauricio
 */
public class DlgNuevoBeneficio extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgNuevoBeneficio.class.getName());
    protected AlmacenamientoEstudiante listaEstudiantes;
    protected AlmacenamientoBeneficios listaBeneficio;
    protected AlmacenamientoBeneficiosEstudiantes listaBeneficioEstudiante;
    protected Beneficios beneficio;
    protected Estudiante estudiante;
    int pos;

    /**
     * Creates new form DlgNuevoBeneficio
     */
    public DlgNuevoBeneficio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DlgNuevoBeneficio(java.awt.Frame parent, boolean modal, AlmacenamientoEstudiante listaEstudiante,
            AlmacenamientoBeneficios listaBeneficio,
            AlmacenamientoBeneficiosEstudiantes listaBeneficioEstudiante,
            Beneficios beneficio) {
        super(parent, modal);
        initComponents();
        this.listaEstudiantes = listaEstudiante;
        this.listaBeneficio = listaBeneficio;
        this.listaBeneficioEstudiante = listaBeneficioEstudiante;
       this.beneficio = beneficio;

    }
    public DlgNuevoBeneficio(java.awt.Frame parent, boolean modal, AlmacenamientoEstudiante listaEstudiante,
            AlmacenamientoBeneficios listaBeneficio,
            AlmacenamientoBeneficiosEstudiantes listaBeneficioEstudiante,
           Estudiante estudiante) {
        super(parent, modal);
        initComponents();
        this.listaEstudiantes = listaEstudiante;
        this.listaBeneficio = listaBeneficio;
        this.listaBeneficioEstudiante = listaBeneficioEstudiante;
   this.estudiante = estudiante;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtIdBeneficio = new javax.swing.JTextField();
        lblNom = new javax.swing.JLabel();
        txtNomBeneficio = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripBeneficio = new javax.swing.JTextField();
        txtMontoBeneficio = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnGuardar)
                .addGap(8, 8, 8)
                .addComponent(btnCancelar)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setText("Id:");

        txtIdBeneficio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNom.setText("Nombre:");

        txtNomBeneficio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción:");

        txtDescripBeneficio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMontoBeneficio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMonto.setText("Monto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNom)
                    .addComponent(lblId)
                    .addComponent(lblDescripcion)
                    .addComponent(lblMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIdBeneficio, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(txtMontoBeneficio))
                    .addComponent(txtDescripBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtIdBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(txtNomBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonto)
                    .addComponent(txtMontoBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Beneficios beneficios = new Beneficios();
        //Validación de campos vacíos
        if (txtIdBeneficio.getText().isBlank()
                || txtNomBeneficio.getText().isBlank()
                || txtDescripBeneficio.getText().isBlank()
                || txtMontoBeneficio.getText().isBlank()) {

            JOptionPane.showMessageDialog(this, "Hay campos vacíos");
        } else {
            //Agregar try/catch
            try {
                beneficios.setIdBeneficio(Integer.parseInt(txtIdBeneficio.getText()));
                beneficios.setNomBeneficio(txtNomBeneficio.getText());
                beneficios.setDescripcion(txtDescripBeneficio.getText());
                beneficios.setMontoBeneficio(Double.parseDouble(txtMontoBeneficio.getText()));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Id y monto deben ser numéricos");
            }

            switch (this.getTitle()) {
                case "Agregar Beneficio" -> {
                    if (listaBeneficio.buscarId(beneficios.getIdBeneficio()) == null) {
                        listaBeneficio.insertarBeneficio(beneficios);
                        JOptionPane.showMessageDialog(this, "Beneficio agregado con éxito");
                        txtIdBeneficio.setText("");
                        txtNomBeneficio.setText("");
                        txtDescripBeneficio.setText("");
                        txtMontoBeneficio.setText("");
                        txtIdBeneficio.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(this, "El id de beneficio ya existe");
                        txtIdBeneficio.setSelectionStart(0);
                        txtIdBeneficio.setSelectionEnd(txtIdBeneficio.getText().length());
                        txtIdBeneficio.requestFocus();
                    }
                }

                case "Editar Beneficio" -> {
                    listaBeneficio.editarBeneficio(pos, beneficios);
                    JOptionPane.showMessageDialog(this, "Beneficio editado con éxito");
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       if (this.getTitle().equals("Editar Beneficio") && beneficio != null) {
        txtIdBeneficio.setText(String.valueOf(beneficio.getIdBeneficio()));
        txtIdBeneficio.setEnabled(false);
        txtNomBeneficio.setText(beneficio.getNomBeneficio());
        txtMontoBeneficio.setText(String.valueOf(beneficio.getMontoBeneficio()));
        txtDescripBeneficio.setText(beneficio.getDescripcion());
    }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgNuevoBeneficio dialog = new DlgNuevoBeneficio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNom;
    private javax.swing.JTextField txtDescripBeneficio;
    private javax.swing.JTextField txtIdBeneficio;
    private javax.swing.JTextField txtMontoBeneficio;
    private javax.swing.JTextField txtNomBeneficio;
    // End of variables declaration//GEN-END:variables
}
