/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import datos.AlmacenamientoEstudiante;
import datos.AlmacenamientoPagosMensuales;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import lógica.PagosMensuales;

/**
 *
 * @author Génesis Leiva
 * @author Ariana Araya
 */
public class DlgPlanillaPagoMensual extends javax.swing.JDialog {

    private DefaultTableModel tblModel;
    protected AlmacenamientoPagosMensuales listaPagosMesuales;
    protected AlmacenamientoEstudiante listaEstudiante;
    protected String mesSelec;
    protected  int anioSelec;
    protected ArrayList<PagosMensuales> pagosActuales;

    /**
     * Creates new form DlgPlanillaPagoMensual
     */
    public DlgPlanillaPagoMensual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DlgPlanillaPagoMensual(java.awt.Frame parent, boolean modal, AlmacenamientoEstudiante listaEstudiante,
            AlmacenamientoPagosMensuales listaPagosMesuales) {
        super(parent, modal);
        initComponents();
        this.listaEstudiante = listaEstudiante;
        this.listaPagosMesuales = listaPagosMesuales;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanilla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtBeneficiados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblPlanilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPlanilla);

        jLabel1.setText("Total:");

        jLabel2.setText("Beneficiados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBeneficiados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 513, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBeneficiados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (pagosActuales!= null &&  !pagosActuales.isEmpty()){//listaEstudiante != null) {
            // Podés usar variables que guardaste al crear el diálogo o pasarlas como atributo
            cargarDatos(mesSelec, anioSelec, pagosActuales, listaPagosMesuales);
        }
    }//GEN-LAST:event_formWindowActivated

    public void cargarDatos(String mes, int anio, ArrayList<PagosMensuales> pagos, AlmacenamientoPagosMensuales almacenamiento) {
        String[] titulos = {"ID", "Estudiante", "Mes", "Fecha de Pago", "Monto Neto", "Total Beneficios"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        if (pagos == null || pagos.isEmpty()) {
            tblPlanilla.setModel(modelo); // tabla vacía
            return;
        }

        for (PagosMensuales pago : pagos) {
            Object[] fila = {
                pago.getIdPago(),
                pago.getEstudiante(), // Podés mostrar nombre si tenés acceso
                pago.getMes(),
                pago.getFechaPago(),
                String.format("₡ %.2f", pago.getPagoNeto()),
                String.format("₡ %.2f", pago.getTotalBeneficios())
            };
            modelo.addRow(fila);
        }

        tblPlanilla.setModel(modelo);

        // Actualizar campos visuales
        txtTotal.setText(String.format("₡ %.2f", almacenamiento.calcularTotalPlanilla(mes, anio)));
        txtBeneficiados.setText(String.valueOf(almacenamiento.contarEstudiantesPlanilla(mes, anio)));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPlanillaPagoMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPlanillaPagoMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPlanillaPagoMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPlanillaPagoMensual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPlanillaPagoMensual dialog = new DlgPlanillaPagoMensual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlanilla;
    private javax.swing.JTextField txtBeneficiados;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
