/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import datos.AlmacenamientoBeneficios;
import datos.AlmacenamientoBeneficiosEstudiantes;
import datos.AlmacenamientoCarreras;
import datos.AlmacenamientoEstudiante;
import datos.AlmacenamientoPagosMensuales;
import javax.swing.JOptionPane;
import vista.DlgAsignarBeneficios;

/**
 *
 * @author Génesis Leiva
 * @author Ariana Araya
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());
    private AlmacenamientoEstudiante almacenamientoEstudiantes;
    private AlmacenamientoCarreras almacenamientoCarreras;
    private AlmacenamientoBeneficios almacenamientoBeneficios;
    private AlmacenamientoBeneficiosEstudiantes almacenamientoBeneficiosEstudiantes;
    private AlmacenamientoPagosMensuales almacenamientoPagosMensuales;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        initializeStorageObjects();
        setLocationRelativeTo(null);
    }

    private void initializeStorageObjects() {
        almacenamientoEstudiantes = new AlmacenamientoEstudiante();
        almacenamientoCarreras = new AlmacenamientoCarreras();
        almacenamientoBeneficios = new AlmacenamientoBeneficios();
        almacenamientoBeneficiosEstudiantes = new AlmacenamientoBeneficiosEstudiantes();
        almacenamientoPagosMensuales = new AlmacenamientoPagosMensuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnEstudiantes = new javax.swing.JButton();
        btnCarreras = new javax.swing.JButton();
        btnBeneficios = new javax.swing.JButton();
        btnAsignarBeneficios = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemGestionEstudiantes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemGestionCarreras = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemGestionBeneficios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemAsignarBeneficios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemPagosMensuales = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(221, 221, 221));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estudiantes.png"))); // NOI18N
        btnEstudiantes.setText("Estudiantes");
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });

        btnCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pasantia.png"))); // NOI18N
        btnCarreras.setText("Carreras");
        btnCarreras.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCarreras.setMaximumSize(new java.awt.Dimension(90, 23));
        btnCarreras.setMinimumSize(new java.awt.Dimension(90, 23));
        btnCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrerasActionPerformed(evt);
            }
        });

        btnBeneficios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beneficios.png"))); // NOI18N
        btnBeneficios.setText("Beneficios");
        btnBeneficios.setMaximumSize(new java.awt.Dimension(90, 23));
        btnBeneficios.setMinimumSize(new java.awt.Dimension(90, 23));
        btnBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeneficiosActionPerformed(evt);
            }
        });

        btnAsignarBeneficios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asignar (2).png"))); // NOI18N
        btnAsignarBeneficios.setText("Asignar Beneficios");
        btnAsignarBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarBeneficiosActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btnSalir.setText("Salir");

        btnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dinero.png"))); // NOI18N
        btnPagos.setText("Pagos");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignarBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(btnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        itemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Estudiantes");

        itemGestionEstudiantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemGestionEstudiantes.setText("Gestión de Estudiantes");
        itemGestionEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionEstudiantesActionPerformed(evt);
            }
        });
        jMenu2.add(itemGestionEstudiantes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Carreras");

        itemGestionCarreras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemGestionCarreras.setText("Gestión Carreras");
        itemGestionCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionCarrerasActionPerformed(evt);
            }
        });
        jMenu3.add(itemGestionCarreras);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Beneficios");

        itemGestionBeneficios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemGestionBeneficios.setText("Gestión de Beneficios");
        itemGestionBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionBeneficiosActionPerformed(evt);
            }
        });
        jMenu4.add(itemGestionBeneficios);
        jMenu4.add(jSeparator1);

        itemAsignarBeneficios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemAsignarBeneficios.setText("Asignar Beneficios");
        itemAsignarBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarBeneficiosActionPerformed(evt);
            }
        });
        jMenu4.add(itemAsignarBeneficios);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Pagos");

        itemPagosMensuales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemPagosMensuales.setText("Pagos Mensuales");
        itemPagosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPagosMensualesActionPerformed(evt);
            }
        });
        jMenu5.add(itemPagosMensuales);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ayuda");

        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        jMenu6.add(itemAcercaDe);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        // TODO add your handling code here:
        mostrarAcercaDe();
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        DlgGestionEstudiantes dialog = new DlgGestionEstudiantes(this, rootPaneCheckingEnabled, almacenamientoEstudiantes, almacenamientoCarreras, almacenamientoBeneficiosEstudiantes, almacenamientoBeneficios);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrerasActionPerformed
        abrirGestionCarreras();
    }//GEN-LAST:event_btnCarrerasActionPerformed

    private void btnBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeneficiosActionPerformed
        abrirGestionBeneficios();
    }//GEN-LAST:event_btnBeneficiosActionPerformed

    private void btnAsignarBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarBeneficiosActionPerformed

        DlgAsignarBeneficios dlg = new DlgAsignarBeneficios(
                this, rootPaneCheckingEnabled,
                almacenamientoEstudiantes,
                almacenamientoBeneficios,
                almacenamientoBeneficiosEstudiantes
        );

        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);


    }//GEN-LAST:event_btnAsignarBeneficiosActionPerformed

    private void itemGestionCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionCarrerasActionPerformed
        DlgGestionCarreras dialog = new DlgGestionCarreras(this, rootPaneCheckingEnabled, almacenamientoCarreras);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemGestionCarrerasActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        if (almacenamientoEstudiantes == null || almacenamientoBeneficios == null
                || almacenamientoBeneficiosEstudiantes == null || almacenamientoPagosMensuales == null) {

            JOptionPane.showMessageDialog(this, "Error: las listas no están inicializadas.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el diálogo de Pagos Mensuales
        DlgPagosMensuales dlg = new DlgPagosMensuales(
                this,
                true,
                almacenamientoEstudiantes,
                almacenamientoBeneficios,
                almacenamientoBeneficiosEstudiantes,
                almacenamientoPagosMensuales
        );

        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnPagosActionPerformed

    private void itemGestionEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionEstudiantesActionPerformed
        // TODO add your handling code here:
        DlgGestionEstudiantes dialog = new DlgGestionEstudiantes(this, rootPaneCheckingEnabled, almacenamientoEstudiantes, almacenamientoCarreras, almacenamientoBeneficiosEstudiantes, almacenamientoBeneficios);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemGestionEstudiantesActionPerformed

    private void itemGestionBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionBeneficiosActionPerformed
        // TODO add your handling code here:
        DlgGestionBeneficios dialog = new DlgGestionBeneficios(this, rootPaneCheckingEnabled, almacenamientoEstudiantes, almacenamientoBeneficios, almacenamientoBeneficiosEstudiantes);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemGestionBeneficiosActionPerformed

    private void itemAsignarBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarBeneficiosActionPerformed
        // TODO add your handling code here:
        DlgAsignarBeneficios dialog = new DlgAsignarBeneficios(this, true, almacenamientoEstudiantes, almacenamientoBeneficios, almacenamientoBeneficiosEstudiantes);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemAsignarBeneficiosActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        // TODO add your handling code here:

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea salir?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra la aplicación
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemPagosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPagosMensualesActionPerformed
        if (almacenamientoEstudiantes == null || almacenamientoBeneficios == null
                || almacenamientoBeneficiosEstudiantes == null || almacenamientoPagosMensuales == null) {

            JOptionPane.showMessageDialog(this, "Error: las listas no están inicializadas.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el diálogo de Pagos Mensuales
        DlgPagosMensuales dlgPagos = new DlgPagosMensuales(this, true, almacenamientoEstudiantes, almacenamientoBeneficios, almacenamientoBeneficiosEstudiantes, almacenamientoPagosMensuales);

        dlgPagos.setLocationRelativeTo(this); // centrar
        dlgPagos.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_itemPagosMensualesActionPerformed
    // Métodos para abrir las ventanas

    private void abrirGestionEstudiantes() {
        try {
            DlgGestionEstudiantes dialog = new DlgGestionEstudiantes(this, true,
                    almacenamientoEstudiantes, almacenamientoCarreras, almacenamientoBeneficiosEstudiantes, almacenamientoBeneficios);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir gestión de estudiantes: " + e.getMessage());
        }
    }

    private void abrirGestionCarreras() {
        try {
            DlgGestionCarreras dialog = new DlgGestionCarreras(this, true, almacenamientoCarreras);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir gestión de carreras: " + e.getMessage());
        }
    }

    private void abrirGestionBeneficios() {
        try {
            DlgGestionBeneficios dialog = new DlgGestionBeneficios(this, true, almacenamientoBeneficios);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir gestión de beneficios: " + e.getMessage());
        }
    }

    private void abrirAsignarBeneficios() {
        try {
            DlgAsignarBeneficios dialog = new DlgAsignarBeneficios(this, true,
                    almacenamientoEstudiantes, almacenamientoBeneficios, almacenamientoBeneficiosEstudiantes);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir asignación de beneficios: " + e.getMessage());
        }
    }

    private void abrirPagosMensuales() {
        try {
            DlgPagosMensuales dialog = new DlgPagosMensuales(this, true,
                    almacenamientoEstudiantes, almacenamientoBeneficios,
                    almacenamientoBeneficiosEstudiantes, almacenamientoPagosMensuales);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir pagos mensuales: " + e.getMessage());
        }
    }

    private void mostrarAcercaDe() {
        String mensaje = "Sistema de Control de Beneficios Estudiantiles\n\n"
                + "Universidad Técnica Nacional\n"
                + "Sede de Guanacaste\n\n"
                + "Desarrollado por:\n"
                + "• Génesis Leiva\n"
                + "• Ariana Araya\n\n"
                + "Curso: Programación I\n"
                + "Prof.: Ing. Jonathan Moreno Núñez\n\n"
                + "Versión 1.0 - 2025";

        JOptionPane.showMessageDialog(this, mensaje, "Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarBeneficios;
    private javax.swing.JButton btnBeneficios;
    private javax.swing.JButton btnCarreras;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemAsignarBeneficios;
    private javax.swing.JMenuItem itemGestionBeneficios;
    private javax.swing.JMenuItem itemGestionCarreras;
    private javax.swing.JMenuItem itemGestionEstudiantes;
    private javax.swing.JMenuItem itemPagosMensuales;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
